<a href="https://colab.research.google.com/github/sivabharathi-k/sivabharathi-codebooster-2026/blob/main/Day2/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd
import matplotlib as plt
import warnings
warnings.filterwarnings('ignore')

print("All libraries imported successfully!")
print(f"pandas version: {pd.__version__}")
print(f"sqlite3 version: {sqlite3.version}")

All libraries imported successfully!
pandas version: 2.2.2
sqlite3 version: 2.6.0

In [5]:


df = pd.read_csv('student_performance.csv')

print(f"Dataset Loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"Columns: {df.columns.tolist()}")

Dataset Loaded: 30 students, 13 columns
Columns: ['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [8]:
conn = sqlite3.connect('college.db')
cursor=conn.cursor()
df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)
cursor.execute('SELECT count(*) from students')
count=cursor.fetchone()[0]
print(f"Database 'college.db' create successfully")
print(f"Table 'students' has {count} rows")
cursor.close()
conn.close()

Database 'college.db' create successfully
Table 'students' has 30 rows

In [13]:
def run_query(query, title):
    conn = sqlite3.connect('college.db')
    df_result = pd.read_sql_query(query, conn)
    conn.close()
    print(title)
    display(df_result)
    return df_result

In [12]:
query1="""
select student_id,name,department,math_score,attendance_percentage from students limit 10
"""
result=run_query(query1,"Query1: first 10 students")

Query1: first 10 students

,student_id,name,department,math_score,attendance_percentage
0,1001,Aarav Sharma,Computer Science,85,92
1,1002,Priya Patel,Computer Science,76,87
2,1003,Rohit Verma,Electronics,65,78
3,1004,Sneha Reddy,Mechanical,70,95
4,1005,Arjun Nair,Computer Science,92,90
5,1006,Meera Joshi,Electronics,58,72
6,1007,Kiran Kumar,Civil,73,85
7,1008,Divya Singh,Computer Science,88,96
8,1009,Rahul Mishra,Mechanical,62,68
9,1010,Ananya Das,Computer Science,95,98

In [14]:
query2="""
select student_id,name from students limit 5
"""
result=run_query(query2,"Query2: first 5 students")

Query2: first 10 students

   student_id          name
0        1001  Aarav Sharma
1        1002   Priya Patel
2        1003   Rohit Verma
3        1004   Sneha Reddy
4        1005    Arjun Nair

In [20]:
query3="""
select name,department,math_score from students order by math_score desc limit 5
"""
result=run_query(query3,"Query3: first 5 students")

Query3: first 5 students

             name        department  math_score
0      Ananya Das  Computer Science          95
1     Tanvi Mehta  Computer Science          93
2      Arjun Nair  Computer Science          92
3  Akanksha Yadav  Computer Science          91
4  Swati Kulkarni  Computer Science          90

In [23]:
query4="""
select name,math_score,programming_score,attendance_percentage from students where department='Computer Science' limit 10
"""
result=run_query(query4,"Query4: first 10 students from Computer Science")

Query4: first 10 students from Computer Science

             name  math_score  programming_score  attendance_percentage
0    Aarav Sharma          85                 91                     92
1     Priya Patel          76                 79                     87
2      Arjun Nair          92                 95                     90
3     Divya Singh          88                 93                     96
4      Ananya Das          95                 97                     98
5      Suresh Rao          83                 88                     88
6     Ajay Tiwari          71                 76                     75
7  Swati Kulkarni          90                 92                     94
8    Nisha Kapoor          79                 83                     89
9     Tanvi Mehta          93                 96                     97

In [ ]:
uery4="""
select name,math_score,programming_score,attendance_percentage from students where department='Computer Science' limit 10
"""
result=run_query(query4,"Query4: first 10 students from Computer Science")

In [24]:
query5="""
select name, department, attendance_percentage from students where attendance_percentage > 90 and department != 'Civil'
"""
result=run_query(query5,"Query5: Students with high attendance (excluding Civil department)")

Query5: Students with high attendance (excluding Civil department)

             name        department  attendance_percentage
0    Aarav Sharma  Computer Science                     92
1     Sneha Reddy        Mechanical                     95
2     Divya Singh  Computer Science                     96
3      Ananya Das  Computer Science                     98
4   Kavya Nambiar        Mechanical                     91
5    Ritu Agarwal       Electronics                     93
6  Swati Kulkarni  Computer Science                     94
7     Tanvi Mehta  Computer Science                     97
8       Amit Bose  Computer Science                     91
9  Akanksha Yadav  Computer Science                     95

In [25]:
query6=""" select distinct department from students
"""
result=run_query(query6,"Query6: Distinct")

Query6: Students with high attendance (excluding Civil department)

         department
0  Computer Science
1       Electronics
2        Mechanical
3             Civil

In [27]:
query7=""" select name, department from students where department in ('Computer Science','Civil')
"""
result=run_query(query7,"Query7: Mutiple values ")

Query7: Mutiple values

              name        department
0     Aarav Sharma  Computer Science
1      Priya Patel  Computer Science
2       Arjun Nair  Computer Science
3      Kiran Kumar             Civil
4      Divya Singh  Computer Science
5       Ananya Das  Computer Science
6      Pooja Gupta             Civil
7       Suresh Rao  Computer Science
8      Ajay Tiwari  Computer Science
9     Manoj Pandey             Civil
10  Swati Kulkarni  Computer Science
11    Nisha Kapoor  Computer Science
12     Tanvi Mehta  Computer Science
13    Sanjay Dubey             Civil
14       Amit Bose  Computer Science
15   Gaurav Shukla  Computer Science
16   Sunita Pillai             Civil
17  Akanksha Yadav  Computer Science

In [28]:
query6="""
select name,attendance_percentage
from students
where attendance_percentage between 80 AND 90
"""
result=run_query(query6,"Query6: students with attendance between 80 and 90")

Query6: students with attendance between 80 and 90

             name  attendance_percentage
0     Priya Patel                     87
1      Arjun Nair                     90
2     Kiran Kumar                     85
3     Vikram Iyer                     83
4     Pooja Gupta                     80
5      Suresh Rao                     88
6    Nisha Kapoor                     89
7   Preeti Saxena                     86
8      Rekha Nair                     82
9   Gaurav Shukla                     87
10     Nitin Jain                     84